### ISSUE TITLE
Error bars for madflow histograms

### ISSUE THREAD

**Issue by marcorossi5** [N3PDF/madflow#16]
We have to add the error bars to our plots.

As far as I know madgraph generates the theoretical error bars varying the scales involved in the process inside a pdfset (muR, muF).

This information is encoded in the LHE file inside the <weightgroup> tag in the banner (which is a legend) and in the <rwgt> tag for each event (gives a single weight for each setting).

Unfortunately we do not have yet this information ready in our LheWriter.

How do we want to make the error bars in our plots then?

Perhaps just making multiple runs with the same settings, collecting multiple histograms and plotting just mean and standard deviation of them?

**Comment by scarlehoff** [comment]
Done
