### ISSUE TITLE
Error when I run integrate_example.py (param_card_path)

### ISSUE THREAD

**Issue by GabrielePalazzo** [N3PDF/madflow#21]
If I try to run integrate_example.py in the examples folder I get the following error message:

```
python3 integrate_example.py -p /tmp/mad_1oxsthid --run /tmp/madldve069e/Events/run_01/
[INFO] (pdfflow.pflow) Loading member 0 from NNPDF31_nnlo_as_0118
Traceback (most recent call last):
  File "integrate_example.py", line 339, in <module>
    model_params = get_model_param(model)
TypeError: get_model_param() missing 1 required positional argument: 'param_card_path'
```

Let me know if you need more information.

Thanks in advance,
Gabriele Palazzo

**Comment by scarlehoff** [comment]
Hi @GabrielePalazzo, sorry about that, that example should've actually been removed (I've done so now, it was basically a script for debugging :P). Thanks for the heads up!

To use `madflow` please use the `madflow` script or some of the other examples (such as `cuts_example.py`).

Thanks!
