### ISSUE TITLE
Error generating histograms using madflow script

### ISSUE THREAD

**Issue by GabrielePalazzo** [N3PDF/madflow#22]
Hi,

if I run madflow from the command line
```madflow -o OutputDir/ --histograms```
the program stops with the following message:
```[  179.028480] Out of memory: Killed process 2519 (madflow) total-vm:28929604kB, anon-rss:6805084kB, file-rss:92160kB, shmem-rss:268288kB, UID:1000 pgtables:19680kB oom_score_adj:0```

If I don't use the ```--histograms``` option, the program runs fine. The examples that generate histograms work perfectly.

Let me know if you need more information.

Thanks in advance,
Gabriele Palazzo

**Comment by scarlehoff** [comment]
Could you add some information on the system you are running (GPU, CPU? Which ones? How much RAM the GPU and the system has?)

**Comment by GabrielePalazzo** [comment]
I'm using my laptop:
Ubuntu 20.04
The CPU is Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (8 GB of memory)
The GPU is GP106M [GeForce GTX 1060 Mobile] (6 GB of memory)

The program is running on the graphics card, however whenever I use the ```--histograms``` option I see very high system memory usage (exceeding 8 GB).
